// 한국 시중/지방/저축/인터넷 은행 목록 (KFTC 표준 코드 기준)
// 자주 쓰이는 순서대로 정렬
export const KOREAN_BANKS: Array<{ code: string; name: string }> = [
  { code: "004", name: "KB국민은행" },
  { code: "088", name: "신한은행" },
  { code: "020", name: "우리은행" },
  { code: "081", name: "하나은행" },
  { code: "011", name: "NH농협은행" },
  { code: "090", name: "카카오뱅크" },
  { code: "089", name: "케이뱅크" },
  { code: "092", name: "토스뱅크" },
  { code: "003", name: "IBK기업은행" },
  { code: "023", name: "SC제일은행" },
  { code: "027", name: "한국씨티은행" },
  { code: "002", name: "산업은행" },
  { code: "071", name: "우체국" },
  { code: "031", name: "대구은행" },
  { code: "032", name: "부산은행" },
  { code: "034", name: "광주은행" },
  { code: "035", name: "제주은행" },
  { code: "037", name: "전북은행" },
  { code: "039", name: "경남은행" },
  { code: "045", name: "새마을금고" },
  { code: "048", name: "신협" },
  { code: "050", name: "저축은행중앙회" },
  { code: "064", name: "산림조합" },
  { code: "007", name: "수협은행" },
  { code: "012", name: "단위농협" },
];
